This notebook uses Python to explore Linear Algebra

In [1]:
import numpy as np
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.array([[1],[2],[3]])
print(M.shape)

(3, 3)


In [2]:
print(v.shape)

(3, 1)


In [3]:
print(3*M)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [4]:
print(M.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
print(np.linalg.inv(M))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [1]:
import numpy as np
A = np.array([[6,-1],[2,3]])
print(A)
print(A.shape)

[[ 6 -1]
 [ 2  3]]
(2, 2)


In [2]:
w, v = np.linalg.eig(A)
print(w)
print(v)

[5. 4.]
[[0.70710678 0.4472136 ]
 [0.70710678 0.89442719]]
